import './globals.css'
import { Inter, Ubuntu } from 'next/font/google'
import Header from "./components/header"
import Navbar from './components/navbar'

const inter = Inter({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
})

const ubuntu = Ubuntu({
  weight: '500',
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ubuntu'
})

export const metadata = {
  title: 'Peter Fan',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html 
      lang="en" 
      className={`${ubuntu.variable}`}>
      <body 
        className='
        antialiased font-ubuntu text-black bg-green-100 dark:text-white dark:bg-[#111010]
        max-w-6xl flex flex-col 
        my-3 mx-3 md:mx-auto'>
        <Header/>
        <Navbar/>
        <main className='flex flex-col items-center text-center
          px-3 py-3 md:py-6 md:px-6
          bg-pink-100'>
          {children}
        </main>
      </body>
    </html>
  )
}